project:
  type: website

website:
  title: "Página Personal JAPT"
  navbar:
    left:
      - href: about.qmd
        text: Sobre mí
      - href: index.qmd
        text: Link tree
      - href: projects.qmd
        text: Proyectos
format:
  html:
    # include-in-header: styles.css
    theme: cosmo
    css: styles.css
    toc: true
output-folder: docs

